FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the Python package located in the current directory
RUN pip install .

# Run the command 'ragposium ingest' when the container starts
CMD ["ragposium", "start"]