services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/data
    # environment:
    #   - SOME_ENV_VAR=your_value

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "6123:8080"
    depends_on:
      - chroma