networks:
  net:
    driver: bridge
services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    networks:
      - net

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: api
    ports:
      - "6123:8080"
    volumes:
      - ./kaggle-data:/kaggle-data
    depends_on:
      - chroma
    networks:
      - net

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
      args:
        - VITE_RAGPOSIUM_URL=https://ragposium.com/api/
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - net
    depends_on:
      - api
      - frontend
