FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app


COPY src/ /app/src/
COPY pyproject.toml /app/
COPY README.md /app/

ENV UV_HTTP_TIMEOUT 120
RUN uv pip install -e . --system

CMD ["ragposium", "start"]